
"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase/client";
import {useI18n} from "@/i18n/LanguageProvider";

type Settings={ccp_account:string;account_holder:string;payment_methods:string;instructions:string};
const empty:Settings={ccp_account:"",account_holder:"",payment_methods:"CCP",instructions:""};
export default function PaymentSettingsPage(){const {dir,t}=useI18n();const [s,setS]=useState<Settings>(empty);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [msg,setMsg]=useState("");useEffect(()=>{(async()=>{const {data}=await supabase.auth.getSession();const r=await fetch("/api/admin/payment-settings",{headers:{Authorization:`Bearer ${data.session?.access_token||""}`}});const d=await r.json();if(d.settings)setS({...empty,...d.settings});setLoading(false)})()},[]);async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setMsg("");const {data}=await supabase.auth.getSession();const r=await fetch("/api/admin/payment-settings",{method:"PUT",headers:{Authorization:`Bearer ${data.session?.access_token||""}`,"Content-Type":"application/json"},body:JSON.stringify(s)});const d=await r.json();if(!r.ok)setMsg(d.error||t.common.error);else setMsg(t.feedback.paymentSettingsSaveSuccess);setSaving(false)}return <main dir={dir} className="min-h-screen bg-zinc-50 py-8"><div className="mx-auto max-w-4xl px-4 sm:px-6"><h1 className="text-3xl font-bold text-zinc-900">{t.adminPaymentSettings.title}</h1><p className="mt-2 text-sm text-zinc-500">{t.adminPaymentSettings.subtitle}</p><form onSubmit={save} className="mt-6 space-y-5 rounded-3xl border border-zinc-200 bg-white p-6"><label className="block text-sm font-medium">{t.adminPaymentSettings.ccpAccount}<input value={s.ccp_account} onChange={e=>setS({...s,ccp_account:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3" placeholder={t.adminPaymentSettings.ccpPlaceholder}/></label><label className="block text-sm font-medium">{t.adminPaymentSettings.accountHolder}<input value={s.account_holder} onChange={e=>setS({...s,account_holder:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-medium">{t.adminPaymentSettings.paymentMethods}<input value={s.payment_methods} onChange={e=>setS({...s,payment_methods:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3" placeholder="CCP, BaridiMob..."/></label><label className="block text-sm font-medium">{t.adminPaymentSettings.instructions}<textarea value={s.instructions} onChange={e=>setS({...s,instructions:e.target.value})} className="mt-2 min-h-48 w-full rounded-xl border px-4 py-3 leading-7" placeholder={t.adminPaymentSettings.instructionsPlaceholder}/></label><button disabled={saving||loading} className="rounded-xl bg-zinc-900 px-6 py-3 font-semibold text-white disabled:opacity-60">{saving?t.common.saving:t.common.save}</button>{msg&&<p className="rounded-xl bg-zinc-50 p-4 text-sm">{msg}</p>}</form></div></main>}
