"use client";
import Link from "next/link";
import LanguageSwitcher from "@/components/i18n/LanguageSwitcher";
import { useI18n } from "@/i18n/LanguageProvider";
import { PLAN_LABELS } from "@/config/plans";

const themes = [
  ["Minimal", "واجهة نظيفة تركز على المنتجات"], ["Elegant", "تجربة راقية للعلامات الراقية"], ["Modern", "تصميم عصري سريع وواضح"], ["Fashion", "أسلوب بصري جريء للأزياء"], ["Beauty", "واجهة ناعمة لمنتجات الجمال"]
];
export default function LandingPage() {
  const { t, dir } = useI18n();
  return <main dir={dir} className="min-h-screen bg-white text-zinc-900">
    <header className="sticky top-0 z-40 border-b border-zinc-100/80 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8">
      <Link href="/" className="text-xl font-black tracking-tight">Nexora</Link>
      <nav className="hidden items-center gap-6 text-sm text-zinc-600 md:flex"><a href="#about">{t.nav.about}</a><a href="#features">{t.nav.features}</a><a href="#plans">{t.nav.plans}</a></nav>
      <div className="flex items-center gap-2"><LanguageSwitcher/><Link href="/auth" className="hidden rounded-xl px-4 py-2 text-sm font-medium sm:inline-flex">{t.nav.login}</Link><Link href="/auth?mode=signup" className="rounded-xl bg-zinc-900 px-4 py-2 text-sm font-semibold text-white">{t.nav.createStore}</Link></div>
    </div></header>
    <section className="relative overflow-hidden"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-28"><div><span className="rounded-full bg-zinc-100 px-4 py-2 text-xs font-semibold text-zinc-600">E-commerce, simplified</span><h1 className="mt-6 text-5xl font-black tracking-tight sm:text-6xl">ابني متجرك، وركّزي على البيع.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-600">Nexora يمنحك البنية الكاملة لإنشاء متجر إلكتروني: منتجات، صور، سلة، طلبات، تخصيص بصري، وواجهة متجر جاهزة.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/auth?mode=signup" className="rounded-2xl bg-zinc-900 px-6 py-3.5 font-semibold text-white">ابدئي إنشاء متجرك</Link><a href="#how" className="rounded-2xl border border-zinc-200 px-6 py-3.5 font-semibold">اكتشفي كيف يعمل</a></div></div><div className="rounded-[2rem] border border-zinc-200 bg-zinc-50 p-5 shadow-2xl shadow-zinc-200/40"><div className="rounded-3xl bg-white p-5"><div className="flex items-center justify-between border-b pb-4"><b>Nexora Store</b><span className="h-2 w-2 rounded-full bg-emerald-500"/></div><div className="grid grid-cols-2 gap-3 py-5"><div className="h-32 rounded-2xl bg-zinc-100"/><div className="h-32 rounded-2xl bg-zinc-100"/><div className="h-7 rounded-xl bg-zinc-100"/><div className="h-7 rounded-xl bg-zinc-100"/></div></div></div></div></section>
    <section id="about" className="border-y border-zinc-100 bg-zinc-50"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-zinc-400">About Nexora</p><h2 className="mt-3 text-3xl font-bold">منصة واحدة بدل عشرات الأدوات.</h2><p className="mt-4 leading-7 text-zinc-600">بدل بناء موقع التجارة الإلكترونية من الصفر، Nexora تعطيك أساسًا جاهزًا وتترك لك ما يهم فعلًا: منتجاتك، علامتك، وتجربة عملائك.</p></div></div></section>
    <section id="features" className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold">كل الأساسيات موجودة</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["إدارة المنتجات والصور", "سلة ودفع وطلبات", "Themes وتخصيص المتجر", "لوحة تحكم وإدارة الاشتراك"].map((x)=><div key={x} className="rounded-3xl border border-zinc-200 p-6"><div className="mb-8 h-10 w-10 rounded-2xl bg-zinc-900"/><h3 className="font-bold">{x}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">مصممة لتعمل ضمن نفس تجربة Nexora بدون تعقيد.</p></div>)}</div></section>
    <section id="how" className="bg-zinc-900 text-white"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold">كيف يعمل Nexora؟</h2><div className="mt-10 grid gap-6 md:grid-cols-4">{["أنشئي حسابك", "أنشئي متجرك", "اختاري الخطة وأرسلي إثبات الدفع", "فعّلي المتجر وابدئي البيع"].map((x,i)=><div key={x} className="rounded-3xl border border-white/10 p-6"><span className="text-sm text-zinc-400">0{i+1}</span><h3 className="mt-8 font-bold">{x}</h3></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-zinc-400">Themes</p><h2 className="mt-3 text-3xl font-bold">اختاري الشخصية البصرية لمتجرك.</h2></div><Link href="/auth?mode=signup" className="font-semibold underline">ابدئي الآن</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{themes.map(([name,desc],i)=><div key={name} className="overflow-hidden rounded-3xl border border-zinc-200"><div className="aspect-[4/3] bg-gradient-to-br from-zinc-100 via-white to-zinc-200 p-4"><div className="h-full rounded-2xl border border-zinc-200 bg-white/70 p-3"><div className="h-2 w-1/2 rounded bg-zinc-200"/><div className="mt-4 grid grid-cols-2 gap-2"><div className="h-20 rounded-xl bg-zinc-100"/><div className="h-20 rounded-xl bg-zinc-100"/></div></div></div><div className="p-4"><b>{name}</b><p className="mt-1 text-xs leading-5 text-zinc-500">{desc}</p></div></div>)}</div></section>
    <section id="plans" className="bg-zinc-50"><div className="mx-auto max-w-5xl px-4 py-20 sm:px-6"><div className="text-center"><h2 className="text-3xl font-bold">خطط واضحة</h2><p className="mt-3 text-zinc-500">اختر الخطة التي تناسب مرحلة متجرك. الأسعار النهائية تُحدد من إعدادات Nexora المركزية.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{(Object.keys(PLAN_LABELS) as Array<keyof typeof PLAN_LABELS>).map(plan=><div key={plan} className={`rounded-3xl border bg-white p-7 ${plan==='business'?'border-zinc-900':'border-zinc-200'}`}><span className="text-sm text-zinc-400">Nexora</span><h3 className="mt-2 text-2xl font-bold">{PLAN_LABELS[plan]}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{plan==='starter'?'الأساسيات لإنشاء وتشغيل متجر إلكتروني.':'مزايا Starter مع Themes وتخصيصات متقدمة.'}</p><Link href="/auth?mode=signup" className="mt-6 inline-flex rounded-xl bg-zinc-900 px-5 py-3 text-sm font-semibold text-white">{t.plans.choose}</Link></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="rounded-[2rem] bg-zinc-100 p-8 text-center sm:p-12"><h2 className="text-3xl font-bold">جاهزة لبناء متجرك؟</h2><p className="mx-auto mt-3 max-w-xl text-zinc-600">ابدئي بالحساب، وسنقودك خلال إنشاء المتجر، الاشتراك، والتحقق.</p><Link href="/auth?mode=signup" className="mt-7 inline-flex rounded-2xl bg-zinc-900 px-7 py-3.5 font-semibold text-white">{t.nav.createStore}</Link></div></section>
    <footer className="border-t border-zinc-100"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 text-sm text-zinc-500 sm:px-6 md:flex-row md:items-center md:justify-between"><span>© Nexora</span><div className="flex gap-5"><a href="#about">{t.nav.about}</a><a href="#features">{t.nav.features}</a><Link href="/auth">{t.nav.login}</Link></div></div></footer>
  </main>;
}
